### ISSUE TITLE
broken links for the yaml files

### ISSUE THREAD

**Issue by DiogoConstantino** [canonical/k8s-snap#904]
The following links for assets on the repository are broken:

https://github.com/canonical/cluster-api-k8s/releases/latest/bootstrap-components.yaml
https://github.com/canonical/cluster-api-k8s/releases/latest/control-plane-components.yaml

---
Document: src/capi/tutorial/getting-started.md

**Comment by DiogoConstantino** [comment]
The correct links are:
https://github.com/canonical/cluster-api-k8s/releases/latest/download/bootstrap-components.yaml
https://github.com/canonical/cluster-api-k8s/releases/latest/download/control-plane-components.yaml

**Comment by HomayoonAlimohammadi** [comment]
Hi @DiogoConstantino!
Thanks a lot for noticing these links! So these links are _supposed to be_ like this. I get that it's a bit confusing but `cluster-api` internals expect such a format. 
Here's an example config file in the CAPI book: https://cluster-api.sigs.k8s.io/clusterctl/configuration
Also here's how these providers are defined and shipped with `clusterctl` command: https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/config/providers_client.go#L367-L371

I would say that we may as well remove that `clusterctl.yaml` config file instructions now that `Canonical Kubernetes Platform` is in the official list of control plane and bootstrap providers baked in the `clusterctl`.

Again, thank you so much for bringing this up!
I'm therefore closing this issue. Let us know if there's anything that we should have a look into further.

**Comment by HomayoonAlimohammadi** [comment]
To dig a bit deeper on this (just because why not?), here is the place CAPI adds the `download` keyword to the url: https://github.com/kubernetes-sigs/cluster-api/blob/main/cmd/clusterctl/client/repository/repository_github.go#L405
But still your concern is very valid and is also already discussed in the CAPI repo (but I guess they forgot or ignored it?): https://github.com/kubernetes-sigs/cluster-api/issues/2830

**Comment by HomayoonAlimohammadi** [comment]
Let's see if we can get anywhere with this PR: https://github.com/kubernetes-sigs/cluster-api/pull/11595

**Comment by HomayoonAlimohammadi** [comment]
Just as a follow up on this issue, I made a mistake of assuming that valid URLs _can not_ be parsed by clusterctl, while the truth is that invalid URLs _can also_ be parsed. That's why the docs originally had those invalid URLs and still worked. The PR on cluster-api repo is closed as it's technically not needed.
